### ISSUE TITLE
NotificationID

### ISSUE THREAD

**Issue by Elias288** [Elias288/Seguimiento_Comida#71]
Al enviar notificación verificar si el usuario está conectado.

[10/5/2023, 10:51:26 a. m.] TypeError: Cannot read properties of undefined (reading 'socketId')
﻿at emitNewNotificacion (/app/src/sockets.js:141:90)
﻿at Socket.<anonymous> (/app/src/sockets.js:114:17)
﻿at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Elias288** [comment]
![Captura de pantalla 2023-05-10 105456](https://github.com/Elias288/Seguimiento_Comida/assets/69608624/8b34e8b9-50c8-411a-8a6b-4d5af741abbf)
